version = 0.1

[default.deploy.parameters]
stack_name = "caleb-transcribe-pipeline"
resolve_s3 = true
s3_prefix = "caleb-transcribe-pipeline"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "RawBucketName=\"media-raw-caleb\" AudioBucketName=\"media-audio-caleb\" TranscriptsBucketName=\"media-transcripts-caleb\""
